project_name: tf-arm

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: tf-arm
    main: ./cmd
    binary: tf-arm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: tf-arm
    builds:
      - tf-arm
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: suer
    name: tf-arm
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

brews:
  - name: tf-arm
    repository:
      owner: suer
      name: homebrew-tap
    homepage: https://github.com/suer/tf-arm
    description: "Terraform State ARM64 Analyzer - Identify AWS resources that can be migrated to ARM64"
    license: MIT
    test: |
      system "#{bin}/tf-arm --help"
    install: |
      bin.install "tf-arm"